services:
  sentineliq-test:
    build:
      context: .
      dockerfile: Dockerfile.local-test
    container_name: sentineliq-harvest-test
    ports:
      - "3000:3000"
    env_file:
      - .env
      - key.env
      - .env.container
    environment:
      # Variables spécifiques au conteneur de test optimisé pour Puppeteer
      - DOCKER_ENV=true
      - CONTAINER_ENV=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - CORTEX_MODE=container
      - NODE_OPTIONS=--max-old-space-size=256
      # Variables Supabase chargées automatiquement depuis key.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Logs pour debug
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
